### ISSUE TITLE
mechanics show

### ISSUE THREAD

**Issue by Bigzay00** [Boom1053/crypto-wrld-issues#1]
there's a problem with the mechanics shop the ls customs location one.
![image](https://user-images.githubusercontent.com/97485393/148857611-4c60a907-35a1-49b7-927d-396a05c73aa6.png)
![image](https://user-images.githubusercontent.com/97485393/148857647-ad76c5d9-637c-41d8-b140-0a6cfa570a93.png)

**Comment by Boom1053** [comment]
Coords was screwed up in the config.

(fixed)
