### ISSUE TITLE
boss menu not in the office

### ISSUE THREAD

**Issue by Bigzay00** [Boom1053/crypto-wrld-issues#2]
![image](https://user-images.githubusercontent.com/97485393/149002420-cf95c2e4-b887-42e0-9967-3b623a2b5d1c.png)

**Comment by Boom1053** [comment]
Where exactly would u like the boss menu?

**Comment by Bigzay00** [comment]
I liked it in the office as it gives the feel that it should be there behind the desk at the computer

**Comment by Boom1053** [comment]
Fixed
